name: flutter_base_project_mvvm
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7
  easy_localization_loader: ^2.0.2
  get_it: ^8.0.3
  shared_preferences: ^2.2.3
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1
  fluttertoast: ^8.2.8
  equatable: ^2.0.5
  provider: ^6.1.2
  flutter_flavor: ^3.1.4
  flutter_dotenv: ^5.1.0
  keyboard_actions: ^4.2.0
  in_app_review: ^2.0.10
  package_info_plus: ^8.1.1
  device_info_plus: ^11.1.1
  connectivity_plus: ^6.1.3
  firebase_remote_config: ^5.4.2
  url_launcher: ^6.3.1
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  google_mobile_ads: ^5.3.1
  share_plus: ^10.1.4
  flutter_animate: ^4.5.2
  camera: ^0.11.1
  image_picker: ^1.1.2
  path: ^1.9.0
  image: ^4.5.4
  flutter_image_compress: ^2.4.0
  image_cropper: ^9.1.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  api_repo: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# TODO: Currently native splash icon is blank icon with same color as background color
# You can use your app background color here but then also change the icon (as currently its a blank background colored image) 
flutter_native_splash:
  color: "#1E1E1E"
  image: "assets/images/splash_icon.png"
  android: true
  ios: true
  web: false
  android_12:
    color: "#1E1E1E"
    icon_background_color: "#1E1E1E"
    image: "assets/images/splash_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - .env

  fonts:
    - family: Inter
      fonts:
      - asset: assets/fonts/Inter_18pt-Regular.ttf


